config/routes.rb
Rails.application.routes.draw do
  
  get 'reservations/create'
  root 'top#index'#welcome画面をtop#indexへ変更する
  
  get 'users/account', to: 'users#account'
  get 'users/profile', to: 'users#profile'
  get 'rooms/posts', to: 'rooms#posts'
  get 'rooms/search', to: 'rooms#search'
  post 'reservations/confirm', to: 'reservations#confirm'
  post 'reservations/back'
  post 'reservations/complete', to: 'reservations#complete'
  
  resources :users, only: [:update]
  resources :rooms
  resources :reservations, only: [:index, :confirm, :complete]
  
  devise_for :users,
    controllers: {
    :confirmations => 'users/confirmations',
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :passwords => 'users/passwords'
    }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :room
 
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  
  def index
    @reservations = Reservation.all
  end
  
  def confirm
    @reservation = Reservation.new(permit_params)
    @room = @reservation.room
    @days = (@reservation.end_date - @reservation.start_date).to_i
    @total_price = @reservation.persons * @days * @room.price
  end
  
  def complete
    @reservation = Reservation.new(permit_params)
    @room = @reservation.room
    @reservation.save
  end
    
  private
  
  def permit_params
    @attr = params.require(:reservation).permit(:start_date, :end_date, :persons, :days, :total_price, :room_id)
  end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/complete.html.erb
<div class = "container-fiuld user">
  <div class = "row">
    <div class = "col-md-12 user-view">
      <div class = "user-view-box">
        <div class = "update-content">
          <div class = "row">
            <label class = "col-md-3">予約した部屋</label>
            <div class = "col-md-9">
              <a href = "/rooms/<%= @room.id %>"><%= @room.name %></a>
            </div>
          </div>
        </div>
        <div class = "update-content">
          <div class = "row">
            <label class = "col-md-3">開始日</label>
            <div class = "col-md-9">
              <%= @reservation.start_date.strftime('%Y年%m月%d日') %>
            </div>
          </div>
        </div>
        <div class = "update-content">
          <div class = "row">
            <label class = "col-md-3">終了日</label>
            <div class = "col-md-9">
              <%= @reservation.end_date.strftime('%Y年%m月%d日') %>
            </div>
          </div>
        </div>
        <div class = "update-content">
          <div class = "row">
            <label class = "col-md-3">価格</label>
            <div class = "col-md-9">
              <%= @reservation.total_price %>円
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/reservations/confirm.html.erb
<div class = "container reservations-new">
  <div class = "row">
    <div class = "col-6 offset-3">
      <div class = "reservations-new-nav">
        <h4 class = "reservations-new-check-content">予約内容確認</h4>
        <h5 class = "price-icon">
          <%= @room.price %> / 日
        </h5>
        <div class = "reservations-new-date-select">
          <%= form_for @reservation, method: :post, url: reservations_complete_path do |f| %>
            <%= f.label :start_date, "開始日" %>
            <%= f.text_field :start_date, class: "form-control mb-4", readonly: "readonly" %>
            <%= f.label :end_date, "終了日" %>
            <%= f.text_field :end_date, class: "form-control mb-4", readonly: "readonly" %>
            <h6 class = "reservations-new-check-content">□使用日数：<%= @days %></h6>
            <%= f.hidden_field :days, value: @days %>
            <h6 class = "reservations-new-check-content">□人数：<%= @reservation.persons %></h6>
            <%= f.hidden_field :persons %>
            <%= f.label :total_price, "合計金額" %>
            <%= f.text_field :total_price, class: "form-control mb-4", value: @total_price, readonly: "readonly" %>
            <p class = "reservations-new-check-content">上記内容でよろしければ「予約を確定」を押してください</p>
            <%= f.hidden_field :room_id, value: @room.id %>
            <%= f.submit "予約を確定", class: "btn btn-primary form-control my-3" %>
            <a class = "btn btn-secondary form-control" href = "/rooms/<%= @room.id %>">ルーム詳細に戻る</a>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/reservations/index.html.erb
<div class = "container-fiuld reservations">
  <h4 class = "pb-4">予約済みルーム一覧</h4>
  <table>
    <thead>
      <tr align = "center">
        <th>ルーム画像</th>
        <th>ルーム名</th>
        <th>ルーム紹介</th>
        <th>合計料金</th>
        <th>開始日</th>
        <th>終了日</th>
        <th>予約確定日時</th>
      </tr>
    </thead>
      <tbody>
        <% @reservations.each do |reservation| %>
          <tr>
            <td>
              <a href = "/rooms/<%= reservation.room.id %>">
                <% if reservation.room.room_image? %>
                  <img class = "reservations-image" src = "<%= reservation.room.room_image %>">
                <% else %>
                  <img class = "reservations-image" src = "/assets/room_default.png">
                <% end %>
              </a>
            </td>
            <td class = "posts-name">
              <a href = "/rooms/<%= reservation.room.id %>">
                <%= reservation.room.name %>
              </a>
            </td>
            <td class = "posts-content">
              <%= reservation.room.introduction %>
            </td>
            <td class = "price-icon">
              <%= reservation.total_price %>
            </td>
            <td><%= reservation.start_date %></td>
            <td><%= reservation.end_date %></td>
            <td><%= reservation.created_at %></td>
          </tr>
        <% end %>
      </tbody>
  </table>
</div>