config/routes.rb
Rails.application.routes.draw do
  
  get 'reservations/create'
  root 'top#index'#welcome画面をtop#indexへ変更する
  
  get 'users/account', to: 'users#account'
  get 'users/profile', to: 'users#profile'
  get 'rooms/posts', to: 'rooms#posts'
  get 'rooms/search', to: 'rooms#search'
  post 'reservations/confirm', to: 'reservations#confirm'
  post 'reservations/back'
  post 'reservations/complete', to: 'reservations#complete'
  
  resources :users, only: [:update]
  resources :rooms
  resources :reservations, only: [:index, :confirm, :complete]
  
  devise_for :users,
    controllers: {
    :confirmations => 'users/confirmations',
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :passwords => 'users/passwords'
    }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
  has_many :reservations
  
  mount_uploader :room_image, RoomImageUploader
  
  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true
  validates :address, presence: true
  
  def self.search(address,introduction)
    where(["address like? OR introduction like?", "%#{address}%", "%#{introduction}%"])
  end
  
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  
  def posts
    @rooms = current_user.rooms
  end
  
  def new
    @room = Room.new
    @id = current_user.id
  end
  
  def create
    @room = Room.new(params.required(:room).permit(:name, :introduction, :price, :address, :room_image, :user_id))
    if @room.save
      flash[:notice] = "Room was successfully created"
      redirect_to :root
    else
      render "new"
    end
  end
  
  def show
    @room = Room.find(params[:id])
    @user = @room.user
    @reservation = Reservation.new
  end
  
  def search
    @rooms = Room.search(params[:address],params[:introduction])
    @result = @rooms.count
  end
  
end

app/views/rooms/new.html.erb
<div class = "container-fiuld room-new">
  <div class = "row">
    <div class = "col-lg-2 room-nav room-nav-pc d-lg-block d-none">
      <ul>
        <li class = "active"><a href = "/rooms/new">基本情報</a></li>
      </ul>
    </div>
    <div class = "col-lg-10 room-view">
      <%= render "shared/error", obj: @room %>
      <div class = "room-view-box">
        <%= form_for @room do |f| %>
          <div class = "update-content">
            <div class = "row">
              <h5>ルーム情報登録</h5>
            </div>
          </div>
          <div class = "update-content">
            <div class = "row">
              <%= f.label:name, "ルーム名", class: "col-md-3 required-a" %>
              <%= f.text_field:name, class: "form-control mb-4 col-md-9", placeholder: "ルーム名を入力" %>
            </div>
          </div>
          <div class = "update-content">
            <div class = "row">
              <%= f.label:introduction, "ルーム紹介", class: "col-md-3 required-a" %>
              <%= f.text_area:introduction, class: "form-control mb-4 col-md-9", placeholder: "ルーム説明を入力" %>
            </div>
          </div>
          <div class = "update-content">
            <div class = "row">
              <%= f.label:price, "料金", class: "col-md-3 required-a" %>
              <%= f.number_field:price, class: "form-control mb-4 col-md-9", placeholder: "一日あたりの料金を入力" %>
            </div>
          </div>
          <div class = "update-content">
            <div class = "row">
              <%= f.label:address, "住所", class: "col-md-3 required-a" %>
              <%= f.text_field:address, class: "form-control mb-4 col-md-9", placeholder: "住所を入力" %>
            </div>
          </div>
          <div class = "update-content">
            <div class = "row">
              <%= f.label :room_image, "ルーム画像", class: "col-md-3" %>
              <%= f.file_field :room_image, class: "form-control mb-4 col-md-9", value: "https://presite-potepancamp-rails-02.herokuapp.com/assets/room01.jpg", placeholder: "ルーム画像をアップロード" %>
            </div>
          </div>
          <%= f.hidden_field :user_id, value: @id %>
          <div class = "update-content">
            <div class = "row">
              <%= f.submit "登録", class: "col-md-2 btn btn-primary mx-3" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>

app/views/rooms/posts.html.erb
<div class = "container-fiuld room-posts">
  <h4 class = "pb-4">登録済みルーム一覧</h4>
  <table>
    <thead>
      <tr align = "center">
        <th>ルーム画像</th>
        <th>ルーム名</th>
        <th>ルーム紹介</th>
        <th>料金</th>
        <th>作成日</th>
      </tr>
    </thead>
    <tbody>
      <% @rooms.each do |room| %>
        <tr>
          <td>
            <a href = "<%= room.id %>">
              <% if room.room_image? %>
                <img class = "room-posts-image" src = "<%= room.room_image %>">
              <% else %>
                <img class = "room-posts-image" src = "/assets/room_default.png">
              <% end %>
            </a>
          </td>
          <td class = "posts-name">
            <a href = "<%= room.id %>">
              <%= room.name %>
            </a>
          </td>
          <td class = "posts-content"><%= room.introduction %></td>
          <td class = "price-icon">
            <%= room.price %>
          </td>
          <td><%= room.created_at %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/rooms/search.html.erb
<div class = "container-fiuld room">
  <h4 class = "pb-4">検索結果：<%= @result %></h4>
  <div class = "row">
    <% @rooms.each do |room| %>
      <div class = "col-sm-6 col-lg-4 col-xl-3">
        <div class = "room-frame-inner">
          <a href = "/rooms/<%= room.id %>">
            <div class = "room-image-out">
              <% if room.room_image? %>
                <img class = "room-image" src = "<%= room.room_image %>">
              <% else %>
                <img class = "room-image" src = "/assets/room_default.png">
              <% end %>
            </div>
            <div class = "room-profile">
              <p class = "room-profile-name"><%= room.name %></p>
              <p class = "room-profile-city"><%= room.address %></p>
              <p class = "room-profile-price price-icon">
                <%= room.price %>
              </p>
            </div>
          </a>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/rooms/show.html.erb
<div class = "container room-show">
  <div class = "row">
    <div class = "col-md-8">
      <% if @room.room_image? %>
        <img class = "room-show-image" src = "<%= @room.room_image %>">
      <% else %>
        <img class = "room-show-image" src = "/assets/room_default.png">
      <% end %>
      <div class = "room-show-detile">
        <div class = "room-show-detile-icon">
          <a href = "<%= @room.id %>">
            <% if @user.image? %>
              <img class = "host-icon" src = "<%= @user.image %>">
            <% else %>
              <img class = "host-icon" src = "/assets/default.png">
            <% end %>
          </a>
        </div>
        <div class = "room-show-profile">
          <p class = "room-show-profile-name">
            <%= @room.name %>
          </p>
          <p class = "room-show-profile-address">
            <%= @room.address %>
          </p>
        </div>
      </div>
      <p class = "room-show-detile-content">
        <%= @room.introduction %>
      </p>
    </div>
    <div class = "col-md-4">
      <div class = "room-show-nav">
        <h5 class = "price-icon">
          <%= @room.price %> / 日
        </h5>
        <div class = "room-show-date-select">
          <%= form_for @reservation, method: :post, url: reservations_confirm_path do |f| %>
            <%= f.label :start_date, "開始日" %>
            <%= f.date_field :start_date, class: "form-control mb-4" %>
            <%= f.label :end_date, "開始日" %>
            <%= f.date_field :end_date, class: "form-control mb-4" %>
            <%= f.label :persons, "人数" %>
            <%= f.number_field :persons, class: "form-control mb-4" %>
            <%= f.hidden_field :room_id, value: @room.id %>
            <%= f.submit "予約する", class: "btn btn-primary form-control" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>